

#banco de dados
development:
  # BANCO DE DADOS
  databse_name: 'plataform_development'
  database_host: 'localhost'
  database_username: 'username'
  database_password: 'username'

production:
  # BANCO DE DADOS
  databse_name: 'plataform_production'
  database_host: 'localhost'
  database_username: 'username'
  database_password: 'username'

test:
  # BANCO DE DADOS
  databse_name: 'plataform_test'
  database_host: 'localhost'
  database_username: 'username'
  database_password: 'username'

#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU
