default: &default
  adapter: postgresql
  encoding: utf8

development:
  <<: *default
  host: <%= ENV['database_host'] %>
  database: <%= ENV['databse_name'] %>
  username: <%= ENV['database_username'] %>
  password: <%= ENV['database_password'] %>

test:
  <<: *default
  host: <%= ENV['database_host'] %>
  database: <%= ENV['databse_name'] %>
  username: <%= ENV['database_username'] %>
  password: <%= ENV['database_password'] %>

production:
  <<: *default
  host: 10.36.25.15
  database: plataform_production
  username: postgres
  password: 123456789
